export const custmorData = {
  name: "Anna Anne",
  customer_id: "19901230-4567",
  email: "annaanne@qliro.com",
  phone: "+46721234567",
  street: "Qlirovagen 123",
  pincode: 12345,
  city: "Stockholm",
  country: "Sweden",
  orders: [
    {
      id: 1,
      order_number: 1234567890,
      created: "05 march, 12:33",
      store: "Butik",
      country: "Sweden",
      payment_method: "Invoice",
      payment_type: "Qliro",
      payment_status: "Paid",
      amount: "2310 kr",
      type: "Online",
    },
    {
      id: 2,
      order_number: 1234567891,
      created: "07 march, 14:33",
      store: "Butik",
      country: "United Kingdom",
      payment_method: "Card, .... 1234",
      payment_type: "Visa",
      payment_status: "In progress",
      amount: "3890 kr",
      type: "Instore",
    },
    {
      id: 3,
      order_number: 1234567892,
      created: "09 march, 12:33",
      store: "Butik",
      country: "Norway",
      payment_method: "Card, .... 1234",
      payment_type: "American Express",
      payment_status: "Failed",
      amount: "1134 kr",
      type: "Manual",
    },
    {
      id: 4,
      order_number: 1234567893,
      created: "11 march, 12:33",
      store: "Butik",
      country: "Sweden",
      payment_method: "Paypal",
      payment_type: "Paypal",
      payment_status: "Paid",
      amount: "2310 kr",
      type: "Online",
    },
    {
      id: 5,
      order_number: 1234567894,
      created: "13 march, 12:33",
      store: "Butik",
      country: "United Kingdom",
      payment_method: "Trustly",
      payment_type: "Trustly",
      payment_status: "Paid",
      amount: "1242 kr",
      type: "Manual",
    },
    {
      id: 6,
      order_number: 1234567895,
      created: "15 march, 12:33",
      store: "Butik",
      country: "Sweden",
      payment_method: "Invoice",
      payment_type: "Visa",
      payment_status: "Paid",
      amount: "3310 kr",
      type: "Online",
    },
    {
      id: 7,
      order_number: 1234567896,
      created: "17 march, 12:33",
      store: "Butik",
      country: "Norway",
      payment_method: "Invoice",
      payment_type: "Qliro",
      payment_status: "Paid",
      amount: "4310 kr",
      type: "Instore",
    },
    {
      id: 8,
      order_number: 1234567897,
      created: "19 march, 12:33",
      store: "Butik",
      country: "United Kingdom",
      payment_method: "Invoice",
      payment_type: "Paypal",
      payment_status: "Paid",
      amount: "4730 kr",
      type: "Manual",
    },
    {
      id: 9,
      order_number: 1234567898,
      created: "21 march, 12:33",
      store: "Butik",
      country: "Sweden",
      payment_method: "Invoice",
      payment_type: "Qliro",
      payment_status: "Falied",
      amount: "2350 kr",
      type: "Online",
    },
    {
      id: 10,
      order_number: 1234567899,
      created: "24 march, 12:33",
      store: "Butik",
      country: "Norway",
      payment_method: "Invoice",
      payment_type: "American Express",
      payment_status: "In progress",
      amount: "7420 kr",
      type: "Online",
    },
  ],
}
