export const custmorData = {
  name: 'Anna Anne',
  customer_id: '19901230-4567',
  email: 'annaanne@qliro.com',
  phone: '+46721234567',
  street: 'Qlirovagen 123',
  areacode: 12345,
  city: 'Stockholm',
  country: 'Sweden',
  orders: [
    {
      id: 1,
      order_number: 1234567890,
      created: '05 maj, 12:33',
      store: 'Butik X',
      country: 'Sweden',
      payment_method: 'Invoice',
      payment_type: 'Qliro',
      payment_status: 'Paid',
      amount: '2310 kr',
      type: 'Online',
    },
    {
      id: 2,
      order_number: 1234567890,
      created: '16 maj, 12:33',
      store: 'Butik X',
      country: 'United Kingdom',
      payment_method: 'Card, .... 1234',
      payment_type: 'Visa',
      payment_status: 'In progress',
      amount: '3890 kr',
      type: 'Instore',
    },
    {
      id: 3,
      order_number: 1234567890,
      created: '20 maj, 12:33',
      store: 'Butik X',
      country: 'Norway',
      payment_method: 'Card, .... 1234',
      payment_type: 'American Express',
      payment_status: 'Failed',
      amount: '1134 kr',
      type: 'Manual',
    },
    {
      id: 4,
      order_number: 1234567890,
      created: '24 maj, 12:33',
      store: 'Butik X',
      country: 'Sweden',
      payment_method: 'Paypal',
      payment_type: 'Paypal',
      payment_status: 'In progress',
      amount: '2310 kr',
      type: 'Online',
    },
    {
      id: 5,
      order_number: 1234567890,
      created: '30 maj, 12:33',
      store: 'Butik X',
      country: 'United Kingdom',
      payment_method: 'Trustly',
      payment_type: 'Trustly',
      payment_status: 'Paid',
      amount: '1242 kr',
      type: 'Manual',
    },
    {
      id: 6,
      order_number: 1234567890,
      created: '31 maj, 12:33',
      store: 'Butik X',
      country: 'Sweden',
      payment_type: 'Visa',
      payment_method: 'Card, .... 1234',
      payment_status: 'Paid',
      amount: '3310 kr',
      type: 'Online',
    },
    {
      id: 7,
      order_number: 1234567890,
      created: '3 june, 12:33',
      store: 'Butik X',
      country: 'Norway',
      payment_method: 'Invoice',
      payment_type: 'Qliro',
      payment_status: 'Paid',
      amount: '4310 kr',
      type: 'Instore',
    },
    {
      id: 8,
      order_number: 1234567890,
      created: '6 june, 12:33',
      store: 'Butik X',
      country: 'United Kingdom',
      payment_method: 'Invoice',
      payment_type: 'Paypal',
      payment_status: 'Paid',
      amount: '4730 kr',
      type: 'Manual',
    },
    {
      id: 9,
      order_number: 1234567890,
      created: '8 june, 12:33',
      store: 'Butik X',
      country: 'Sweden',
      payment_method: 'Invoice',
      payment_type: 'Qliro',
      payment_status: 'Falied',
      amount: '2350 kr',
      type: 'Online',
    },
    {
      id: 10,
      order_number: 1234567890,
      created: '10 june, 12:33',
      store: 'Butik X',
      country: 'Norway',
      payment_type: 'American Express',
      payment_method: 'Card, .... 1234',
      payment_status: 'In progress',
      amount: '7420 kr',
      type: 'Online',
    },
  ],
};
